# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "node-best-practice"
  config.vm.box_url = "ubuntu-14.04-amd64-vbox.box"
  config.ssh.forward_agent = true

  config.vm.define "local" , primary: true do |config|

    config.vm.network "forwarded_port", guest: 9090, host: 9090

    config.vm.network "private_network", ip: "10.0.0.2"

    config.vm.synced_folder "../", "/vagrant"

    config.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", "2048"]
    end
  end
end